### ISSUE TITLE
PostCSS output result is empty in windows machine

### ISSUE THREAD

**Issue by anuraghazra** [tailwindlabs/tailwindcss-jit#107]
### What version of @tailwindcss/jit are you using?

0.1.3

### What version of Node.js are you using?

v14.16.0

### What browser are you using?

N/A

### What operating system are you using?

Windows 10 (Windows_NT x64 10.0.19041)

### Reproduction repository

N/A

Even after applying the fixes in #106 

I could not get the tests to pass, all tests are failing. 
And I noticed that the output of `postcss`'s `result.css` only contains the base styles, thus snapshots aren't matching. 

Test name: 01-basic-usage.test
Output:

```js
    * {
        --tw-shadow: 0 0 #0000;
        --tw-ring-inset: var(--tw-empty,/*!*/ /*!*/);
        --tw-ring-offset-width: 0px;
        --tw-ring-offset-color: #fff;
        --tw-ring-color: rgba(59, 130, 246, 0.5);
        --tw-ring-offset-shadow: 0 0 #0000;
        --tw-ring-shadow: 0 0 #0000
    }
```

Screenshot: 
![image](https://user-images.githubusercontent.com/35374649/111623605-96747180-8810-11eb-99b7-4adb0caa634e.png)

NOTE: This seems to be a windows specific issue because it works fine on mac.

**Comment by adamwathan** [comment]
Any chance you have it cloned into a path that contains spaces? Appears to be issues around that with Windows at the moment.

**Comment by adamwathan** [comment]
Also for reproduction repository you were supposed to provide an awesome YouTube video, I'll let you off with a warning this time though 🧐😅

**Comment by anuraghazra** [comment]
> Any chance you have it cloned into a path that contains spaces? Appears to be issues around that with Windows at the moment.

Yes it does contains spaces but i already have fixes applied from #106 and it is working. 

But the issue is that the test files are failing because snapshots not matching up (since final result from postcss is empty)

> okay i will try to create a screencast of the error.

**Comment by anuraghazra** [comment]
Here's the video (it's not much, very straightforward):

https://user-images.githubusercontent.com/35374649/111632262-4dc1b600-881a-11eb-9fd7-d1b79609f8be.mp4

**Comment by adamwathan** [comment]
Ah man I think my joke didn't come across properly with the YouTube stuff, what I meant is to just share a video you really like from YouTube, even Rick Roll me if you're truly evil 😅  Thanks for this though I will take a look at it when I have a chance and see if we can figure out the issue!

**Comment by anuraghazra** [comment]
> Ah man I think my joke didn't come across properly with the YouTube stuff, what I meant is to just share a video you really like from YouTube, even Rick Roll me if you're truly evil 😅 Thanks for this though I will take a look at it when I have a chance and see if we can figure out the issue!

Oh gosh... haha... my bad, I missed the joke 😆 😆 

> well speaking of funny youtube videos you can check this out: https://www.youtube.com/watch?v=EDbSi5cN63U 😆
