### ISSUE TITLE
Fails when input is stdin

### ISSUE THREAD

**Issue by bep** [tailwindlabs/tailwindcss-jit#112]
### What version of @tailwindcss/jit are you using?

v0.1.3

### What version of Node.js are you using?

N/A

### What browser are you using?

N/A

### What operating system are you using?

macOS

### Reproduction repository

N/A

* This is with `TAILWIND_MODE=build` and the CSS passed in to `postcss-cli` via `stdin`:

```bash
Error: ENOENT: no such file or directory, stat '/Users/bep/dev/sites/hugo-starter-tailwindjit-basic/stdin'
```

**Comment by adamwathan** [comment]
Hey thanks for the report! This is ultimately going to be the same issue as #74, so going to track there.
