### ISSUE TITLE
Support for time values like "50ms" "1s"

### ISSUE THREAD

**Issue by drmzio** [tailwindlabs/tailwindcss-jit#115]
### What version of @tailwindcss/jit are you using?

v0.1.3

### What version of Node.js are you using?

v15.11.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

N/A

Tried using a custom duration variant like: `duration-[50ms]` but it doesn't work. Would be nice to have support for time values.

**Comment by bradlc** [comment]
Hey @drmzio. This was actually added in #99 and will be in the next release 👍
