### ISSUE TITLE
Plugin using addUtilities doesn't seem to work

### ISSUE THREAD

**Issue by yet-another-dev** [tailwindlabs/tailwindcss-jit#117]
### What version of @tailwindcss/jit are you using?

v0.1.3

### What version of Node.js are you using?

v14.16.0

### What browser are you using?

Chrome

### What operating system are you using?

macOS

### Reproduction repository

n/a

I use a custom plugin for cross-browser "flex gap" support (see it here: https://github.com/tailwindlabs/tailwindcss/discussions/2316#discussioncomment-409062.).

Sadly, this doesn't seem to be working with JIT.

Will this approach to plugins be supported with JIT?

**Comment by adamwathan** [comment]
Hey! Should work, can you please provide a reproduction repository that shows it not working so we can troubleshoot? It's a required field for a reason 🙂

**Comment by yet-another-dev** [comment]
Alright, it's working now ¯\_(ツ)_/¯

Thanks for confirming it should, Adam.
