### ISSUE TITLE
PostCSS plugin tailwindcss-jit requires PostCSS 8

### ISSUE THREAD

**Issue by MuttakinHasib** [tailwindlabs/tailwindcss-jit#137]
### What version of @tailwindcss/jit are you using?

v0.1.6

### What version of Node.js are you using?

v14.15.1

### What browser are you using?

firefox, Chrome

### What operating system are you using?

macOS

### Reproduction repository

https://github.com/MuttakinHasib/cloudsbay

## Create React App

```http://localhost:3000/```

![Screen Shot 2021-03-22 at 7 47 41 PM](https://user-images.githubusercontent.com/44552983/111999893-9db8b980-8b47-11eb-8473-b48e3d3b755e.png)

![Screen Shot 2021-03-22 at 7 48 03 PM](https://user-images.githubusercontent.com/44552983/111999908-a27d6d80-8b47-11eb-8d6e-74d704372404.png)

![Screen Shot 2021-03-22 at 7 48 15 PM](https://user-images.githubusercontent.com/44552983/111999914-a4dfc780-8b47-11eb-8350-ab036b71bc62.png)

**Comment by adamwathan** [comment]
Hey! Yep this project requires PostCSS v8 as the error mentions. You have an error in your postcss.config.js file as well, you don't need `tailwindcss` _and_ `@tailwindcss/jit`, just `@tailwindcss/jit` as mentioned in the instructions 👍🏻

**Comment by MuttakinHasib** [comment]
how can i use **@tailwindcss/jit** in this project ?

**Comment by adamwathan** [comment]
Create React App unfortunately uses an old version of PostCSS and isn't kept up to date, so you will have to wait until CRA updates their version of PostCSS or use a different tool.

Personally I would recommend [Vite](https://vitejs.dev) as an alternative for anyone who likes CRA — it's a great experience for building CRA-style projects.
