### ISSUE TITLE
Dark mode friendly logo image

### ISSUE THREAD

**Issue by smhmd** [tailwindlabs/tailwindcss-jit#16]
![image](https://user-images.githubusercontent.com/46059092/111196146-43ef4700-85bd-11eb-9cba-d437dd662a43.png)

**Comment by adamwathan** [comment]
Until GitHub lets you use different images for each mode not much we can really do here 🤷 Perfectly readable regardless.

**Comment by smhmd** [comment]
Not even a PNG with a transparent background or an SVG?

**Comment by adamwathan** [comment]
Transparent background would make the text invisible since it would be black on black.
