### ISSUE TITLE
Extending colors not working properly

### ISSUE THREAD

**Issue by hunzaboy** [tailwindlabs/tailwindcss-jit#160]
### What version of @tailwindcss/jit are you using?

v0.1.8

### What version of Node.js are you using?

v14.15.4

### What browser are you using?

Chrome

### What operating system are you using?

MacOS

### Reproduction repository

#

The JIT compiler is unable to compile my colors (especially the 1st one (test1) as shown in the screenshot). The text colors are working but the background variants are not working e.g bg-test1-50 etc

All color-related variants are working for test2 but not for test1 ( as defined in the screenshot)

<img width="468" alt="Screenshot 2021-03-26 at 14 38 16" src="https://user-images.githubusercontent.com/827098/112639910-1a49e180-8e41-11eb-80f5-05d6cfa00778.png">

**Comment by adamwathan** [comment]
Hey! This works as expected here:

<img width="1663" alt="image" src="https://user-images.githubusercontent.com/4323180/112669310-f208b580-8e35-11eb-84de-f01c2ab4192f.png">

Please open a new issue and include a reproduction repository if this is still an issue. Without a reproduction I can only try to reproduce it myself, and if I can't I have to assume it's an issue in your configuration.

**Comment by hunzaboy** [comment]
Hey Adam, 

Thanks for the reply. 

FYI: I think I know why that happened, my config was correct but I was using `@layer utilities`  in my CSS file with some custom code. I removed it and now it is working as expected. Also, I am using NextJs.
