### ISSUE TITLE
[BUG/IDEA] Autocomplete when using matchUtilities

### ISSUE THREAD

**Issue by mr-httdd** [tailwindlabs/tailwindcss-jit#169]
### What version of @tailwindcss/jit are you using?

v0.1.10

### What version of Node.js are you using?

v12.0.0

### What browser are you using?

N/A

### What operating system are you using?

macOS

### Reproduction repository

-

Sorry, this is not entirely related to the work of the module, but may help someone.

I had the idea to use the matchUtilities method in my plugins, but when I use it, Tailwind CSS autocomplete is disabled completely (https://plugins.jetbrains.com/plugin/15321-tailwind-css), can I fix it somehow?

The idea was to add your own classes, similar to sass mixins

**Comment by adamwathan** [comment]
Hey! I'm guessing this has something to do with how Jetbrains has implemented their Tailwind support, since the `matchUtilities` is new to the JIT library. Going to close as nothing we can do about this here I'm afraid 😕
