### ISSUE TITLE
Responsive breakpoints are not working as expected.

### ISSUE THREAD

**Issue by riseno** [tailwindlabs/tailwindcss-jit#194]
### What version of @tailwindcss/jit are you using?

0.1.17

### What version of Node.js are you using?

v15.12.0

### What build tool (or framework if it abstracts the build tool) are you using?

laravel mix

### What browser are you using?

chrome, safari and firefox

### What operating system are you using?

macOS

### Reproduction repository

N/A

responsive breakpoints are not physically switching, for example,

```
<div class="flex flex-col lg:flex-row space-y-2 p-2">
...
</div>
```

It should switch to `flex-row` when the width is more than `lg:` min-width, but currently it's doing nothing. And i open the inspect tool in chrome, it does have the class show up but crossed out. 

![Screenshot 2021-04-01 at 1 55 12 AM](https://user-images.githubusercontent.com/14790405/113189075-5fc93d00-928d-11eb-9389-8ffc7dc9e2d6.png)

Any ideas?

**Comment by adamwathan** [comment]
Hey! Sorry, as mentioned in the issue template issues without a reproduction repository will be closed. Please open a new issue with a reproduction repository.
