### ISSUE TITLE
Gulp task not finishing

### ISSUE THREAD

**Issue by rfrerebe** [tailwindlabs/tailwindcss-jit#195]
### What version of @tailwindcss/jit are you using?

v0.1.18

### What version of Node.js are you using?

v12.21.0

### What build tool (or framework if it abstracts the build tool) are you using?

gulp

### What browser are you using?

Chrome

### What operating system are you using?

Windows with WSL2

### Reproduction repository

https://github.com/rfrerebe/jit-repro

Hello,

Running `npm run build` (or `gulp build`) on repro will start a task that never finish
Changing the purge options in `tailwind.config.css` will have the expected behaviour (ie task ending).

**Comment by adamwathan** [comment]
Hey! Basically guaranteed you just aren't setting the environment variables you need to as outlined in the docs here:

![image](https://user-images.githubusercontent.com/4323180/113213070-a1ce9080-9245-11eb-8887-ce2fc0c6b5db.png)

**Comment by austenc** [comment]
Also ran into this when implementing with Laravel Mix.

Adam's notes (and the docs) are correct -- you likely just need to set `TAILWIND_MODE=build` in your command.
