### ISSUE TITLE
Feature request: grid-cols[repeat] and grid-cols[minmax]

### ISSUE THREAD

**Issue by wtchnm** [tailwindlabs/tailwindcss-jit#20]
Hello!

Thank you very much for the amazing work!
The JIT compiler worked like a charm for me on [Vitamin](https://github.com/wtchnm/Vitamin).
The only thing that I need to completely remove CSS Modules from the demo is the functional notation support for grid-template-columns.
I'll be happy to write a PR if you can point me in the right direction.

Cheers!

**Comment by adamwathan** [comment]
Hey! You can do this already like:

```
grid-cols-[100px,2fr,minmax(1fr,400px)]
```

Just use commas where you would normally use spaces 👍🏻 We'll get this documented sooner or later, stuff is still super early here!

**Comment by wtchnm** [comment]
Thanks! The "-" was missing before the brackets 🤦🏻‍♂️

**Comment by pluscda** [comment]
I have issue when doing : grid-cols-[repeat(10, 200px)]

**Comment by pluscda** [comment]
The grid-cols-[100px,2fr,minmax(1fr,400px)] seems not working either.

**Comment by adamwathan** [comment]
@pluscda Please open a new issue, 99% of the time we don't notice comments on closed issues and have no way of tracking them.

**Comment by pluscda** [comment]
Thanks for reminding and all the hard works for creating tailwind css. This project is great.
