### ISSUE TITLE
Cannot set property 'parent' of undefined when plugins added

### ISSUE THREAD

**Issue by merelinguist** [tailwindlabs/tailwindcss-jit#21]
I’m currently trying to integrate this with a Next.js project, but am receiving this error:

```
error - ./node_modules/tailwindcss/tailwind.css ((webpack)/css-loader/cjs.js??ref--5-oneOf-5-1!(webpack)/postcss-loader/cjs.js??ref--5-oneOf-5-2!./node_modules/tailwindcss/tailwind.css)
TypeError: Cannot set property 'parent' of undefined
```

I can’t seem to reproduce it, but strangely when I remove the plugins from my Tailwind config, Next happily compiles: https://github.com/merelinguist/strove/blob/39a64dc7ef32c36742446e9716cb4781d83d1fcf/tailwind.config.js#L14-L18.

**Comment by chriswdmr** [comment]
Try updating to the latest postcss, I also had this issue but updating it, resolved it for me:
`npm install -D postcss@latest`

**Comment by merelinguist** [comment]
> Try updating to the latest postcss, I also had this issue but updating it, resolved it for me:
> `npm install -D postcss@latest`

This fixed it for me too.

**Comment by mwarger** [comment]
@merelinguist @chriswdmr Would you be able to share more of your config or versions?  I'm still getting the same error after updating to the latest postcss version.

**Comment by elie222** [comment]
Facing same issue. He shared his project in the original post: merelinguist/strove@39a64dc/tailwind.config.js#L14-L18
