### ISSUE TITLE
Possible to run with Laravel Mix?

### ISSUE THREAD

**Issue by klickreflex** [tailwindlabs/tailwindcss-jit#24]
Super pumped to try Tailwind JIT 🤩

I'm having trouble adding it to a Statamic project using Laravel Mix to configure PostCSS, but I'm not even sure if that's the problem or something entirely different.

webpack.mix.js
```js
mix.postCss('resources/css/tailwind.css', 'public/css', [
    require('postcss-import'),
    require('@tailwindcss/jit')({}),
    require('postcss-nested'),
    require('postcss-preset-env')({stage: 0})
])
```

Compilation throws the following error:

```
 Mix
  Compiled with some errors in 1.00s

ERROR in ./resources/css/tailwind.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: Cannot read property 'split' of undefined
    at replaceSelector (/Users/daniel/www/statamic.schreinerei-neub/node_modules/@tailwindcss/jit/src/lib/expandApplyAtRules.js:84:12)
    at /Users/daniel/www/statamic.schreinerei-neub/node_modules/@tailwindcss/jit/src/lib/expandApplyAtRules.js:116:31
    at /Users/daniel/www/statamic.schreinerei-neub/node_modules/postcss/lib/container.js:115:18
    at /Users/daniel/www/statamic.schreinerei-neub/node_modules/postcss/lib/container.js:74:18
    at Root.each (/Users/daniel/www/statamic.schreinerei-neub/node_modules/postcss/lib/container.js:60:16)
    at Root.walk (/Users/daniel/www/statamic.schreinerei-neub/node_modules/postcss/lib/container.js:71:17)
    at Root.walkRules (/Users/daniel/www/statamic.schreinerei-neub/node_modules/postcss/lib/container.js:113:19)
    at /Users/daniel/www/statamic.schreinerei-neub/node_modules/@tailwindcss/jit/src/lib/expandApplyAtRules.js:115:18
    at LazyResult.runOnRoot (/Users/daniel/www/statamic.schreinerei-neub/node_modules/postcss/lib/lazy-result.js:303:16)
    at LazyResult.runAsync (/Users/daniel/www/statamic.schreinerei-neub/node_modules/postcss/lib/lazy-result.js:355:26)
    at processResult (/Users/daniel/www/statamic.schreinerei-neub/node_modules/webpack/lib/NormalModule.js:598:19)
    at /Users/daniel/www/statamic.schreinerei-neub/node_modules/webpack/lib/NormalModule.js:692:5
    at /Users/daniel/www/statamic.schreinerei-neub/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /Users/daniel/www/statamic.schreinerei-neub/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/Users/daniel/www/statamic.schreinerei-neub/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (/Users/daniel/www/statamic.schreinerei-neub/node_modules/postcss-loader/dist/index.js:104:7)

1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack compiled with 2 errors

```

**Comment by barnabasmolnar** [comment]
Any postcss plugin that uses postcss 7 (postcss-preset-env I know for sure does) is unfortunately not compatible with this. 😞

**Comment by Yiddishe-Kop** [comment]
I'm on Laravel Mix v6 & Postcss 8.2.1, still not managing to get it to work.

**Comment by florianbouvot** [comment]
It works like a charm for me.

**Comment by florianbouvot** [comment]
It works like a charm for me (with posts 8), my current setting: https://github.com/florianbouvot/laravel-mix-boilerplate/tree/next

**Comment by thecrypticace** [comment]
This should work fine with Laravel mix v6. The `laravel-mix-tailwind` package isn't strictly necessary and I'm not sure that we've tested it with Mix v6.

**Comment by the-ashraf** [comment]
You can, and its working beautifully, here's my webpack.mix.js

```
const mix = require('laravel-mix');
const tailwindJit = require("@tailwindcss/jit");

mix.js('resources/js/app.js', 'public/js/main.js')
	.vue()
	.sass("resources/css/app.scss", "public/css/main.css")
	.options({
		postCss: [
			tailwindJit,
			require('css-declaration-sorter')({order: 'smacss'})
		],
		autoprefixer: {
			options: {
				browsers: [
					'last 4 versions',
				]
			}
		}

	})
	.extract()
	.version();

```

**Comment by Yiddishe-Kop** [comment]
@the-ashraf I can't figure out why it's not working for me.

This is my setup:

webpack.mix.js:
```js
const tailwindJit = require("@tailwindcss/jit");
//...
.sass('resources/sass/app.scss', 'public/css/app.css')
  .options({
    processCssUrls: false,
    postCss: [
      tailwindJit,
    ],
    autoprefixer: {}
  })
```

**Comment by nordentwickler** [comment]
@Yiddishe-Kop could you post your package.json?

**Comment by Yiddishe-Kop** [comment]
package.json:
```json
{
  "private": true,
  "scripts": {
    "pretty": "prettier --write \"./resources/**/*.{js,vue,json}\"",
    "dev": "npm run development",
    "development": "mix",
    "watch": "mix watch",
    "watch-poll": "mix watch -- --watch-options-poll=1000",
    "hot": "mix watch --hot",
    "build": "npm run production",
    "production": "mix --production"
  },
  "devDependencies": {
    "@braid/vue-formulate": "^2.4.5",
    "@braid/vue-formulate-i18n": "^1.13.0",
    "@inertiajs/inertia": "^0.8.2",
    "@inertiajs/inertia-vue": "^0.5.4",
    "@inertiajs/progress": "^0.2.4",
    "@kazupon/vue-i18n-loader": "^0.5.0",
    "@popperjs/core": "^2.5.3",
    "@tailwindcss/jit": "^0.1.1",
    "@tailwindcss/typography": "^0.4.0",
    "@vue/composition-api": "^1.0.0-beta.13",
    "@vueuse/core": "^4.0.1",
    "@yiddishe-kop/inertia": "^0.8.4",
    "axios": "^0.21.1",
    "canvas-confetti": "^1.3.2",
    "chart.js": "^2.9.4",
    "cross-env": "^7.0.3",
    "date-fns": "^2.16.1",
    "laravel-mix": "^6.0.0",
    "laravel-mix-tailwind": "^0.1.0",
    "lodash": "^4.17.20",
    "portal-vue": "^2.1.7",
    "postcss": "^8.2.8",
    "prettier": "^2.2.1",
    "resolve-url-loader": "^3.1.0",
    "sass": "^1.30.0",
    "sass-loader": "^8.0.2",
    "tailwindcss": "^2.0.3",
    "tailwindcss-rtl": "^0.7.3",
    "vue": "^2.6.12",
    "vue-barcode": "^1.3.0",
    "vue-carousel": "^0.18.0",
    "vue-click-outside": "^1.1.0",
    "vue-cookie": "^1.1.4",
    "vue-i18n": "^8.21.1",
    "vue-infinite-loading": "^2.4.5",
    "vue-loader": "^15.9.6",
    "vue-meta": "^2.4.0",
    "vue-quill-editor": "^3.0.6",
    "vue-select": "^3.11.2",
    "vue-template-compiler": "^2.6.12",
    "vue-tippy": "^4.7.2",
    "vue-tour": "^1.5.0"
  }
}
```

**Comment by nordentwickler** [comment]
Are all these packages PostCss 8 compatible? 

Working example: package.json
```
{
  "main": "index.js",
  "scripts": {
    "dev": "mix",
    "watch": "mix watch",
    "watch-poll": "mix watch -- --watch-options-poll=1000",
    "hot": "mix watch --hot",
    "production": "mix --production"
  },
  "keywords": [],
  "license": "MIT",
  "dependencies": {
    "@tailwindcss/aspect-ratio": "^0.2.0",
    "@tailwindcss/forms": "^0.2.1",
    "autoprefixer": "^10.2.5",
    "vue": "^3.0.7"
  },
  "devDependencies": {
    "@tailwindcss/jit": "^0.1.1",
    "@vue/compiler-sfc": "^3.0.7",
    "browser-sync": "^2.26.14",
    "browser-sync-webpack-plugin": "^2.2.2",
    "cross-env": "^6.0.3",
    "glob-all": "^3.2.1",
    "laravel-mix": "^6.0.13",
    "postcss": "^8.2.8",
    "postcss-loader": "^5.2.0",
    "resolve-url-loader": "^3.1.0",
    "sass": "^1.23.0",
    "sass-loader": "^8.0.0",
    "tailwindcss": "^2.0.3",
    "vue-loader": "^16.1.2",
    "vue-template-compiler": "^2.6.12"
  }
}

```
Working example: webpack.mix.js
```
let mix = require('laravel-mix');
const glob = require('glob-all');
const tailwindJit = require("@tailwindcss/jit");

const BROWSER_SYNC_PROXY = 'schumann2.hub';
const EXTRACT_VENDORS = ['vue'];

mix.setPublicPath('public/');


mix.js('src/scripts/app.js', 'assets/js').vue({
    extractStyles: true,
    globalStyles: false,
    version: 3
});

mix.extract(EXTRACT_VENDORS);

mix.sass("src/styles/app.scss", "assets/css/") // for sass
    .options({
        processCssUrls: false,
        postCss: [
            tailwindJit,
        ],
        autoprefixer: {
            options: {
                browsers: [
                    'last 4 versions',
                ]
            }
        }
    });

mix.browserSync({
    proxy: BROWSER_SYNC_PROXY,
    host: BROWSER_SYNC_PROXY,
    open: 'external',
    files: glob.sync([
        'templates/**/*.twig',
        'src/scripts/**/*.{js,vue}',
        'src/styles/**/*.scss',
        'tailwind.config.js'
    ]),
});


if (mix.inProduction()) {
    mix.version();
}
```
I needed to update everything: laravel mix, post css, vue - all of it.

Thanks to @the-ashraf - adding scss back to the game helped me a lot :)

**Comment by the-ashraf** [comment]
@Yiddishe-Kop i'm taking a wild stab here. try bumping laravel mix to 6.0.11 and try without laravel-mix-tailwind as it seems redundant for what we're trying to achieve.

**Comment by Yiddishe-Kop** [comment]
I'm getting this error now:
```
ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
RangeError: Maximum call stack size exceeded
```

**Comment by igerslike** [comment]
While npm run dev works just fine, run watch doesnt seem to like it :( lets wait as this is fresh still :p wroth the try and very nicely done.

**Comment by grantholle** [comment]
I'm not getting any errors when using `jit`, but it only compiles the reset/normalize part. I'm on Mix v6 as well

```js
mix.js('resources/js/app.js', 'public/js')
  .vue({ version: 3 })
  .disableSuccessNotifications()
  .version()
  .webpackConfig(webpackConfig)
  .postCss('resources/css/app.css', 'public/css', [
    require('postcss-import'),
    require('@tailwindcss/jit'),
    require('postcss-nested'),
  ])
```

**Comment by grantholle** [comment]
Ok, I have it working, I didn't have my purge files configured in my `tailwind.config.js`, which is what it uses to know what to build... 🤦‍♂️

This is amazing!!! Amazing work Tailwind team on this

**Comment by the-ashraf** [comment]
@Yiddishe-Kop in my app.scss i'm using @tailwind instead of @import, not sure if that makes any difference, but in general yes you do need the tailwind directives there.

also look at this from another issue with the same error.
[Try updating to the very latest autoprefixer](https://github.com/tailwindlabs/tailwindcss-jit/issues/29#issuecomment-799748676)

**Comment by GamesmenJordan** [comment]
Although I am not using Laravel, I am experience the same or similar error to the original poster:

```TypeError: Cannot read property 'split' of undefined
    at replaceSelector (***/tailwind/node_modules/@tailwindcss/jit/src/lib/expandApplyAtRules.js:84:12)
    at ***/tailwind/node_modules/@tailwindcss/jit/src/lib/expandApplyAtRules.js:116:31
    at ***/tailwind/node_modules/postcss/lib/container.js:115:18
    at ***/tailwind/node_modules/postcss/lib/container.js:74:18
    at Root.each (***/tailwind/node_modules/postcss/lib/container.js:60:16)
    at Root.walk (***/tailwind/node_modules/postcss/lib/container.js:71:17)
    at Root.walkRules (***/tailwind/node_modules/postcss/lib/container.js:113:19)
    at ***/tailwind/node_modules/@tailwindcss/jit/src/lib/expandApplyAtRules.js:115:18
    at LazyResult.runOnRoot (***/tailwind/node_modules/postcss/lib/lazy-result.js:303:16)
    at LazyResult.runAsync (***/tailwind/node_modules/postcss/lib/lazy-result.js:355:26)

{
  postcssNode: Rule {
    raws: { before: '\n' },
    type: 'rule',
    nodes: [ [Declaration] ],
    selector: '.flex-row',
    lastEach: 3,
    indexes: {},
    parent: Root {
      raws: {},
      nodes: [Array],
      type: 'root',
      lastEach: 1,
      indexes: [Object],
      [Symbol(isClean)]: false
    },
    [Symbol(isClean)]: false
  }
}
```

Excerpt from `package.json`
```
"dependencies": {
        "@tailwindcss/forms": "^0.2.1",
        "@tailwindcss/typography": "^0.3.1",
        "autoprefixer": "^10.2.1",
        "browser-sync": "^2.26.14",
        "csso-cli": "^3.0.0",
        "lodash": "^4.17.20",
        "postcss-import": "^12.0.1",
        "postcss-nested": "^4.2.3",
        "@tailwindcss/jit": "^0.1.1",
        "terser": "^4.7.0"
    },
    "devDependencies": {
        "postcss": "^8.2.4",
        "postcss-cli": "^8.3.1"
    },
    "scripts": {
        "build": "NODE_ENV=development npx postcss tailwind-source.css -o tailwind-output.css",
    },
```

**Comment by nckrtl** [comment]
Checkout the known limitations section: https://github.com/tailwindlabs/tailwindcss-jit

You are getting this error because you use @apply somewhere where its not allowed. I faced the same error and it was because I used @apply within an imported css file. I only manage to get @apply working when using it in a @layer directive. So I can't use @apply in separate css files which I import in the main app.css file.

**Comment by Yiddishe-Kop** [comment]
@nckrtl I think the limitation is on **@apply**ing classes not defined in Tailwind core/plugins/@layer:

> You can only @apply classes that are part of core, generated by plugins, or defined within a @layer rule. You can't @apply arbitrary CSS classes that aren't defined within a @layer rule.

Anyhow, I tried putting all @apply statements inside @layer blocks, but still getting the same error `RangeError: Maximum call stack size exceeded` 🤕

**Comment by nckrtl** [comment]
Yeah my comment was referring to the error @GamesmenJordan is experiencing. Yours has probably another cause.

**Comment by OliverGrimsley** [comment]
> Checkout the known limitations section: https://github.com/tailwindlabs/tailwindcss-jit
> 
> You are getting this error because you use @apply somewhere where its not allowed. I faced the same error and it was because I used @apply within an imported css file. I only manage to get @apply working when using it in a @layer directive. So I can't use @apply in separate css files which I import in the main app.css file.

I had the same issue for custom font-face.  After adding it to the base layer per documentation, I had to remove this in my base component:

```
html {
   @apply font-inter font-light leading-tight;
}
```
Then it magically worked.   And, by magic, I mean my dev build css went from 3MB to 16K 😎

**Comment by CreateSean** [comment]
I tried with mix 5.x and failed, guess I should get around to updating my build process

**Comment by the-ashraf** [comment]
@Yiddishe-Kop, I just saw this somewhere, when using `@import` you have to use `postcss-import`.
I guess switch to `@tailwind` in your `app.scss`

**Comment by klickreflex** [comment]
When removing all custom CSS (and thus any instance of `@apply`) the error is gone indeed and I'll need to double-check my @applys. 

However,  now there's a new error thrown which I'm not sure what to do with:

```
✖ Mix
  Compiled with some errors in 2.25s

ERROR in ./resources/css/tailwind.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
RangeError: Maximum call stack size exceeded
    at Function.keys (<anonymous>)
    at _clone (/Users/daniel/www/statamic.schreinerei-neub/node_modules/postcss-preset-env/node_modules/autoprefixer/lib/prefixer.js:22:42)
    at _clone (/Users/daniel/www/statamic.schreinerei-neub/node_modules/postcss-preset-env/node_modules/autoprefixer/lib/prefixer.js:38:17)
    at _clone (/Users/daniel/www/statamic.schreinerei-neub/node_modules/postcss-preset-env/node_modules/autoprefixer/lib/prefixer.js:38:17)
    at _clone (/Users/daniel/www/statamic.schreinerei-neub/node_modules/postcss-preset-env/node_modules/autoprefixer/lib/prefixer.js:38:17)
    at _clone (/Users/daniel/www/statamic.schreinerei-neub/node_modules/postcss-preset-env/node_modules/autoprefixer/lib/prefixer.js:38:17)
    at _clone (/Users/daniel/www/statamic.schreinerei-neub/node_modules/postcss-preset-env/node_modules/autoprefixer/lib/prefixer.js:38:17)
    at _clone (/Users/daniel/www/statamic.schreinerei-neub/node_modules/postcss-preset-env/node_modules/autoprefixer/lib/prefixer.js:38:17)
    at _clone (/Users/daniel/www/statamic.schreinerei-neub/node_modules/postcss-preset-env/node_modules/autoprefixer/lib/prefixer.js:38:17)
    at _clone (/Users/daniel/www/statamic.schreinerei-neub/node_modules/postcss-preset-env/node_modules/autoprefixer/lib/prefixer.js:38:17)
    at processResult (/Users/daniel/www/statamic.schreinerei-neub/node_modules/webpack/lib/NormalModule.js:598:19)
    at /Users/daniel/www/statamic.schreinerei-neub/node_modules/webpack/lib/NormalModule.js:692:5
    at /Users/daniel/www/statamic.schreinerei-neub/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /Users/daniel/www/statamic.schreinerei-neub/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/Users/daniel/www/statamic.schreinerei-neub/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (/Users/daniel/www/statamic.schreinerei-neub/node_modules/postcss-loader/dist/index.js:104:7)

1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack compiled with 2 errors
```

**Comment by liamja** [comment]
> When removing all custom CSS (and thus any instance of `@apply`) the error is gone indeed and I'll need to double-check my @applys.
> 
> However, now there's a new error thrown which I'm not sure what to do with:
> 
> ```
> ✖ Mix
>   Compiled with some errors in 2.25s
> 
> ERROR in ./resources/css/tailwind.css
> Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
> ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
> RangeError: Maximum call stack size exceeded
>     at Function.keys (<anonymous>)
>     at _clone (/Users/daniel/www/statamic.schreinerei-neub/node_modules/postcss-preset-env/node_modules/autoprefixer/lib/prefixer.js:22:42)
>     at _clone (/Users/daniel/www/statamic.schreinerei-neub/node_modules/postcss-preset-env/node_modules/autoprefixer/lib/prefixer.js:38:17)
>     at _clone (/Users/daniel/www/statamic.schreinerei-neub/node_modules/postcss-preset-env/node_modules/autoprefixer/lib/prefixer.js:38:17)
>     at _clone (/Users/daniel/www/statamic.schreinerei-neub/node_modules/postcss-preset-env/node_modules/autoprefixer/lib/prefixer.js:38:17)
>     at _clone (/Users/daniel/www/statamic.schreinerei-neub/node_modules/postcss-preset-env/node_modules/autoprefixer/lib/prefixer.js:38:17)
>     at _clone (/Users/daniel/www/statamic.schreinerei-neub/node_modules/postcss-preset-env/node_modules/autoprefixer/lib/prefixer.js:38:17)
>     at _clone (/Users/daniel/www/statamic.schreinerei-neub/node_modules/postcss-preset-env/node_modules/autoprefixer/lib/prefixer.js:38:17)
>     at _clone (/Users/daniel/www/statamic.schreinerei-neub/node_modules/postcss-preset-env/node_modules/autoprefixer/lib/prefixer.js:38:17)
>     at _clone (/Users/daniel/www/statamic.schreinerei-neub/node_modules/postcss-preset-env/node_modules/autoprefixer/lib/prefixer.js:38:17)
>     at processResult (/Users/daniel/www/statamic.schreinerei-neub/node_modules/webpack/lib/NormalModule.js:598:19)
>     at /Users/daniel/www/statamic.schreinerei-neub/node_modules/webpack/lib/NormalModule.js:692:5
>     at /Users/daniel/www/statamic.schreinerei-neub/node_modules/loader-runner/lib/LoaderRunner.js:399:11
>     at /Users/daniel/www/statamic.schreinerei-neub/node_modules/loader-runner/lib/LoaderRunner.js:251:18
>     at context.callback (/Users/daniel/www/statamic.schreinerei-neub/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
>     at Object.loader (/Users/daniel/www/statamic.schreinerei-neub/node_modules/postcss-loader/dist/index.js:104:7)
> 
> 1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
> webpack compiled with 2 errors
> ```
> 
> This error goes away when I remove `require('postcss-import'),`, which I can't wrap my head around, because I import my Tailwind directives using `@import` and it still works when removing postcss-import. Is this how it's supposed to be?
> 
> ```
> @import "tailwindcss/base";
> 
> @import "tailwindcss/components";
> 
> @import "tailwindcss/utilities";
> ```
> 
> But this only works until I start importing my custom CSS, then I end up with `@responsive` and `@layers` not being interpreted.

I fixed the `RangeError: Maximum call stack size exceeded` error with `npm install -D autoprefixer@latest`

From the README:

> If you are using autoprefixer, make sure you are on the latest version using npm install -D autoprefixer@latest — there's a bug in older versions that makes it incompatible with this library.

**Comment by klickreflex** [comment]
Thanks @liamja, now I got it working. Here's are the things I did to make it work:

1. Migrate purge options in Tailwind config to array syntax (was object syntax with safelist options configured, just moved safelist into a file as suggested in docs)
2. Update Autoprefixer to latest (10.2.5 as of now)
3. Remove all instances of `@screen` in my custom CSS (in my case I was fine just moving to class prefixes) - is this a known thing though?


Not sure if the issue with `@screen` ist documented already.

**Comment by Yiddishe-Kop** [comment]
Thanks @klickreflex, updating autoprefixer did it for me! 👍
Running `npm install -D autoprefixer@latest` waen't enough, I had to edit the version in package.json to `10.2.5`.

**Comment by gilbitron** [comment]
I got it working running without issue with the `mix` command but when running `mix watch --hot` I got the `Maximum call stack size exceeded` error. A temporary solution is to disable autoprefixer in your mix config:

```
mix.options({ autoprefixer: false });
```

**Comment by TomOudeRengerink** [comment]
When running sass, the styles inside the `@component` directive are not directly updated unless you edit your main sass entry file. This is only happening to imported sass files in the main sass entry file.

Anyone else experiences this issue?

**Comment by adamwathan** [comment]
This should work totally fine as long as you are on the latest version of Mix (v6) and the latest version of Autoprefixer 👍  If anyone is still having issues definitely open a new issue and include a reproduction and I will take a look ❤️

**Comment by CreateSean** [comment]
> 3. Remove all instances of `@screen` in my custom CSS (in my case I was fine just moving to class prefixes) - is this a known thing though?
> 
> Not sure if the issue with `@screen` ist documented already.


As @klickreflex mentioned any use of @screen in your app.css file breaks the tailwind JIT compiler. 

However as soon as you remove it, works perfectly.

**Comment by klickreflex** [comment]
@CreateSeanI narrowed it down to uses of `@apply` _within_ `@screen`, can you confirm?

**Comment by CreateSean** [comment]
> @CreateSean I narrowed it down to uses of `@apply` _within_ `@screen`, can you confirm?

@klickreflex I narrowed it down even further.

It will compile if the @screen is not nested inside a selector and has @apply or if it is nested inside a selector and does not have @apply.

The following works
```
  @screen md {
    .hamburger-icon {
      color:pink;
    }
    .main-nav {
      @apply bg-green-200;
    }
  }
  img {
    @screen md {
      border:2px solid pink;
    }
  }
```


However when @screen is nested inside a selector and has @apply it fails to compile. The following breaks:
```
  .circle-item {
    @screen sm {
      @apply w-auto;
    }
  }```

@adamwathan hope this helps you find this bug.

**Comment by thecrypticace** [comment]
@klickreflex @CreateSean Regarding nested `@screen` + `@apply`: This isn't strictly a bug. postcss-nested doesn't parse this right but we've got no plans to support this at the moment in tailwind itself: https://github.com/tailwindlabs/tailwindcss-jit/issues/76#issuecomment-800538113

However, we do plan to add some better error messages around this.
