### ISSUE TITLE
Enhancement: Calc within brackets

### ISSUE THREAD

**Issue by jshimkoski** [tailwindlabs/tailwindcss-jit#31]
I just thought of a use case for something like this: `md:h-[calc(100vh - 4rem]`.

Possible?

**Comment by adamwathan** [comment]
Hey! This should work already if you remove the spaces (classes can't have spaces unfortunately).

```
md:h-[calc(100vh-4rem)]
```

**Comment by jshimkoski** [comment]
Oh man... this is the greatest thing ever! 🕺
