### ISSUE TITLE
Jekyll front matter breaks CSS parser

### ISSUE THREAD

**Issue by colejd** [tailwindlabs/tailwindcss-jit#41]
In Jekyll, your CSS file [must start with front matter](https://jekyllrb.com/docs/assets/), like so:
```
---
---
```

This is needed to get Jekyll to move the file into your build folder.

~~If you compile this, you get this error: `Error: ENOENT: no such file or directory, stat 'stdin'`.~~ This was a problem specific to my repo. the actual error is:
```
Conversion error: Jekyll::Converters::PostCss encountered an error while converting 'assets/css/main.css':
                    767: unexpected token at ''
```

Anyone have any idea how to get around this? This isn't an issue if you're not using the JIT.

**Comment by adamwathan** [comment]
Hmm I'm surprised this would work without the JIT — that's not valid CSS and even the regular version of Tailwind requires a valid CSS file to parse.

Can you provide a reproduction of it working without JIT and not working with?

**Comment by colejd** [comment]
I think it's not actually the front matter's fault, but I'll link an example anyway. [This PR](https://github.com/colejd/colejd.github.io/pull/5) on my own website's repo adds a minimal implementation of the JIT. The front matter in question is located at `assets/css/main.css`.

It actually looks like the problem occurs when I import Tailwind, e.g.:
```
@import "tailwindcss/base";
@import "tailwindcss/components";
```
(This happens with the `@tailwind` syntax as well.)

That leads to this error:
```
/Users/colejd/.rbenv/versions/2.6.3/lib/ruby/2.6.0/json/common.rb:156:in `parse': 767: unexpected token at '' (JSON::ParserError)
```

In my pipeline, Jekyll ingests files, passes them through PostCSS, and then copies the result to the build folder. Maybe by removing the front matter I'm just excluding the CSS from processing through PostCSS altogether?

**Comment by colejd** [comment]
Narrowing it down... this seems to be an error caused by using postcss-import before the JIT. If you disable the import in [`postcss.config.js`](https://github.com/colejd/colejd.github.io/blob/55cd90377731026c9021114c237273486a94853e/postcss.config.js#L3), the JIT works.

**Comment by colejd** [comment]
Interestingly, if you remove postcss-import and try to use Tailwind's `@tailwind` syntax for imports, you get the same error as above. You don't get it if you use the equivalent `@import "tailwindcss/<something>";` syntax.

**Comment by leevigraham** [comment]
@colejd 

> If you compile this, you get this error: Error: ENOENT: no such file or directory, stat 'stdin'

What was causing that error… I get the same one in my snowpack setup.

**Comment by colejd** [comment]
> @colejd
> 
> > If you compile this, you get this error: Error: ENOENT: no such file or directory, stat 'stdin'
> 
> What was causing that error… I get the same one in my snowpack setup.

Basically, my build-and-watch setup was hiding errors that were happening in the build part of the process. If you run a single build, it'll probably tell you the actual error @leevigraham

**Comment by adamwathan** [comment]
Sounds like this is resolved (I think?), so going to close 👍 If there is still a problem here you think we can look at/fix please open a new issue that includes a minimal reproduction and we can definitely look at it.
