### ISSUE TITLE
Unable to use group-focus

### ISSUE THREAD

**Issue by david-buck** [tailwindlabs/tailwindcss-jit#46]
Even with my old config applied:

` ...
    variants: {
    extend: {
      opacity: ["group-focus"],
    },
    ...`

the group-focus part of this no longer works with JIT:

`"group-hover:opacity-100 group-focus:opacity-100"`

(the `group-hover` still does)

**Comment by alexcroox** [comment]
I get an error when using `@apply group` saying `group` doesn't exist

**Comment by adamwathan** [comment]
Can you provide a reproduction? I just tested this locally and it works as expected:

<img width="940" alt="image" src="https://user-images.githubusercontent.com/4323180/111372212-bc631000-8670-11eb-83c2-42be49539311.png">

**Comment by david-buck** [comment]
I have misidentified the issue here. 

What I was doing was setting `opacity-0 `then had a check for `current` which was also adding `opacity-100` for the current item. This worked previously but probably shouldn't have.
