### ISSUE TITLE
Add autoprefixer in the installation guide of JIT

### ISSUE THREAD

**Issue by subhoghs** [tailwindlabs/tailwindcss-jit#56]
Without autoprefixer it always show this error in every nextjs project I create.
```
Cannot find module 'autoprefixer'
Require stack:
- /home/subho/.cave/apps/private/discord-clone/node_modules/tailwindcss/lib/cli/commands/build.js
- /home/subho/.cave/apps/private/discord-clone/node_modules/tailwindcss/lib/cli/commands/index.js
- /home/subho/.cave/apps/private/discord-clone/node_modules/tailwindcss/lib/cli/main.js
- /home/subho/.cave/apps/private/discord-clone/node_modules/tailwindcss/lib/cli.js
```
As the error is coming from tailwind cli. I guess this error will also show up in projects with other build tools. So also adding autoprefixer to the list would be best I guess `npm install -D @tailwindcss/jit tailwindcss postcss autoprefixer`

**Comment by adamwathan** [comment]
I've added a note related to this, thanks!
