### ISSUE TITLE
Animation not working with important: true

### ISSUE THREAD

**Issue by zigomir** [tailwindlabs/tailwindcss-jit#64]
Hey! Thanks for making this, it's awesome.

I'm having issues using animation with `important: true` in my config file. Seems like `!important` is added to `@keyframes` which breaks the animation.

**Comment by zigomir** [comment]
I'm sorry – I dunno what happened but I can't reproduce this anymore and it all works fine 🤷‍♂️

**Comment by adamwathan** [comment]
Fixed in v0.1.2, thanks!
