### ISSUE TITLE
Using @apply with postcss-nested causes each class to have its own rule

### ISSUE THREAD

**Issue by laymonage** [tailwindlabs/tailwindcss-jit#67]
Thanks for this, it's really cool! I'm using `postcss-nested` in my project and I stumbled upon this bug.

## Description

When using `@apply` with nested rules using `postcss-nested`, each applied class has its own rule. This makes using background color and opacity utilities at the same time impossible.

### CSS

```css
.container {
  /* I use `a` element selector in this example, but using a class selector also doesn't work */
  a {
    @apply bg-blue-800 bg-opacity-10;
    /* or @apply bg-opacity-10 bg-blue-800; same result */
  }
}
```

### With JIT

![image](https://user-images.githubusercontent.com/6379424/111329997-2516b080-86a2-11eb-99b6-7441711447a8.png)
![image](https://user-images.githubusercontent.com/6379424/111328282-aff6ab80-86a0-11eb-8c05-f101cbeedcae.png)

### Without JIT (expected)

![image](https://user-images.githubusercontent.com/6379424/111329835-02849780-86a2-11eb-8a6f-0ffecbe6aabe.png)
![image](https://user-images.githubusercontent.com/6379424/111328804-2693a900-86a1-11eb-976d-674fda65330f.png)

## Reproducible repo

- [`nested-jit`](https://github.com/laymonage/tailwind-jit-nested/tree/nested-jit): `postcss-nested` with JIT, which has the bug as described.
- [`nested-aot`](https://github.com/laymonage/tailwind-jit-nested/tree/nested-aot): `postcss-nested` with AOT. The result is correct and only one rule produced.
- [`nested-jit-separate`](https://github.com/laymonage/tailwind-jit-nested/tree/nested-jit-separate): `postcss-nested` with JIT, but with separate `@apply` for each class. The result is correct, but it produces multiple rules.
- [`nesting-jit`](https://github.com/laymonage/tailwind-jit-nested/tree/nesting-jit): `postcss-nesting` with JIT. The result is correct, but it produces multiple rules.
- [`nesting-aot`](https://github.com/laymonage/tailwind-jit-nested/tree/nesting-aot): `postcss-nesting` with AOT. The result is correct and only one rule produced.

## Notes

I've tried:
- [x] Changing the PostCSS plugins order so that `postcss-nested` comes before `@tailwindcss/jit`, **doesn't work**.
- [x] Using `postcss-nesting`: it **works**, but it still produces separate rules.
- [x] Separating the `@apply` like so:
```css
.container {
  a {
    @apply bg-blue-800;
    @apply bg-opacity-10;
  }
}
```
Which **works**, but it still produces separate results.

This also affects other classes that rely on being applied within the same rule, such as border color and border opacity.

**Comment by lifedup** [comment]
Separate the rules

`
.container {
  a {
    @apply bg-blue-800;
    @apply bg-opacity-10;
  }
}
`

**Comment by lifedup** [comment]
Separate the rules.

`bg-xxx-xxx`  applies the bg color and the default `-tw-bg-opacity` var set to 1 and you have to tell the system to use the one you specify.

Since Tailwind also applies the same variable that `bg-opacity-xxx` does, you must take into account the order CSS is processed.  You also need to specify the CSS in the correct order for it to be applied properly. 

```
.container {
  a {
    @apply bg-opacity-10;
    @apply bg-blue-800;
  }
}
```

**Comment by silvenon** [comment]
It might be related to #76, using the selector `.container a` works.

**Comment by silvenon** [comment]
If I'm not mistaken, using `postcss-nesting` appears to fix your problem! 😃 When using `postcss-nesting` you need to add an extra `&` when nesting, so `& a` instead of just `a`.

**Comment by laymonage** [comment]
@lifedup Thanks for the hint!

It seems to work, but with opacity **after** the background color, so:

```css
.container {
  a {
    @apply bg-blue-800;
    @apply bg-opacity-10;
  }
}
```

Which makes sense because `bg-opacity`  is supposed to override the  `--tw-bg-opacity` of the `bg` color:
![image](https://user-images.githubusercontent.com/6379424/111398619-65a01980-86f6-11eb-9dda-1510ff317dbb.png)

@silvenon Thanks!! I totally forgot about that. Indeed, `postcss-nesting` seems to work. I can use a single `@apply` with both `@apply bg-blue-800 bg-opacity-10` and  `@apply bg-opacity-10 bg-blue-800` and they produce the correct results.

However, using `postcss-nested` or `postcss-nesting` with JIT produces separate rules for each class applied (even if using a single `@apply`), which isn't the case when using AOT. I've cleaned up the reproduction:
- [`nested-jit`](https://github.com/laymonage/tailwind-jit-nested/tree/nested-jit): `postcss-nested` with JIT, which has the bug as described.
- [`nested-aot`](https://github.com/laymonage/tailwind-jit-nested/tree/nested-aot): `postcss-nested` with AOT. The behavior is correct and only one rule produced.
- [`nested-jit-separate`](https://github.com/laymonage/tailwind-jit-nested/tree/nested-jit-separate): `postcss-nested` with JIT, but with separate `@apply` for each class. The behavior is correct, but it produces multiple rules.
- [`nesting-jit`](https://github.com/laymonage/tailwind-jit-nested/tree/nesting-jit): `postcss-nesting` with JIT. The behavior is correct, but it produces multiple rules.
- [`nested-aot`](https://github.com/laymonage/tailwind-jit-nested/tree/nesting-aot): `postcss-nesting` with AOT. The behavior is correct and only one rule produced.

**Comment by lifedup** [comment]
If you happen to be using nextjs,  enable sass and use .scss/sass files.  It keeps the custom classes intact using multiple `@apply` or a single with multiple rules. I use next and this setup and so far it seems to be working as expected.

**Comment by lifedup** [comment]
I use nextjs with sass enabled and am using scss files.  I group my `@apply` rules
```#id {
  @apply flex flex-col-reverse;
  @apply overflow-x-hidden overflow-y-auto;
  @apply z-50;`
 & .content {
    @apply flex flex-col;
    @apply p-safe;
  }
}
 and it seems to work as expected without any other postcss configs or modules.  Note that next is compiling sass first.  If you happen to be using next try to enable sass and using sass/scss files.

**Comment by valse** [comment]
> I use nextjs, enabled sass, and am using scss files. I can now group my `@apply` rules

This is my solution too: I swapped to SASS, removed postcss-nesting plugin and JIT works like a charm!

I had locally memory issues on build too but with JIT enabled my project compiles locally without problem ;)

**Comment by adamwathan** [comment]
Troubleshooted this for a while, I would have expected the solution to be to just put `postcss-nested` _before_ Tailwind in your `postcss.config.js` file:

```js
module.exports = {
  plugins: {
    'postcss-nested': {},
    '@tailwindcss/jit': {},
    autoprefixer: {},
  },
}
```

However this still doesn't work because `postcss-nested` recently migrated to the new PostCSS visitor API which breaks guarantees about which order transforms are performed in.

You can fix this for now by pinning your `postcss-nested` dependency to `5.0.1` and changing the plugin order like I've mentioned above. I'm going to work with the PostCSS team to find out if there's a way to solve this on their end, because it doesn't seem reasonable to me that we should be expected to handle nested CSS ourselves when it's not syntactically valid.

**Comment by adamwathan** [comment]
Another solution is to use `postcss-nesting` (which doesn't use the new visitor API) instead of `postcss-nested`, and again make sure it is first in the plugin list:

```js
module.exports = {
  plugins: {
    'postcss-nesting': {},
    '@tailwindcss/jit': {},
    autoprefixer: {},
  },
}
```

That is what I would recommend at the moment 👍  Going to close with that as the recommended solution but still going to talk to other maintainers about the bigger picture issue here.
