### ISSUE TITLE
Multiple variants not working

### ISSUE THREAD

**Issue by zbeyens** [tailwindlabs/tailwindcss-jit#72]
I ran the command:
`TAILWIND_MODE=watch postcss src/assets/tailwind.css -o src/assets/tailwind.output.css -w` with a component class `hover:underline`, which outputs:

```
.hover\:underline:hover {
  text-decoration: underline;
}
```

Then I modify the component class to `hover:underline focus:underline` which outputs:

```
.focus\:hover\:underline:focus:hover {
  text-decoration: underline;
}
```

Then I revert back the component class to `hover:underline` but it still outputs 
```
.focus\:hover\:underline:focus:hover {
  text-decoration: underline;
}
```

### Requirements
```
"@tailwindcss/jit": "^0.1.1",
"tailwindcss": "^2.0.3",
"postcss": "^8.2.8",
"postcss-cli": "^8.3.1",
"autoprefixer": "^10.2.5",
```

**Comment by adamwathan** [comment]
Hey! I think what you are seeing is just that when you edit HTML, we only add *new* classes, we don't delete old classes even if they aren't used anymore. This is a performance optimization that makes a big difference in incremental builds. Are you 100% sure the `hover:underline` class was removed? If so can you provide a GitHub repo that reproduces?

**Comment by zbeyens** [comment]
Yes it was removing it. The issue was that I've installed tailwindcss-jit at the root of the monorepo (yarn workspaces) while the other ones were in the app package. Moving it to the app dependencies fixed it.

Thanks for your time!
