### ISSUE TITLE
@responsive not generating default class

### ISSUE THREAD

**Issue by Striffly** [tailwindlabs/tailwindcss-jit#75]
The `@responsive` functions generate the responsive classes, but seems to not generate the default class.

Exemple : 
```
@responsive {
  .container-fluid {
    padding-left: var(--container-padding);
    padding-right: var(--container-padding);
  }
}
```

```
.sm:container-fluid {
  padding-left: var(--container-padding);
  padding-right: var(--container-padding);
}

.lg:container-fluid {
  padding-left: var(--container-padding);
  padding-right: var(--container-padding);
}

.xl:container-fluid {
  padding-left: var(--container-padding);
  padding-right: var(--container-padding);
}

# .container-fluid {} is missing
```

**Comment by adamwathan** [comment]
Hey! Make sure you have `@tailwind utilities` in your CSS, anything in a `@responsive` rule is automatically dumped into the `utilities` layer if you don't manually wrap it in a layer.

<img width="1302" alt="image" src="https://user-images.githubusercontent.com/4323180/111373069-dc470380-8671-11eb-8d89-5290533ab345.png">

Works as expected then 👍🏻

**Comment by Striffly** [comment]
Indeed the problem came exactly from there... I still can't understand why all responsive classes are generated, except the default one
Anyway, thanks !
