### ISSUE TITLE
Translate doesn't appear to support arbitrary values

### ISSUE THREAD

**Issue by pheuter** [tailwindlabs/tailwindcss-jit#77]
```html
<div class="mr-[-9.5rem]"></div>
<div class="translate-x-[-9.5rem]"></div>
```

The first `<div>` works as expected, but the second one does not appear to have the corresponding Tailwind utility class generated.

**Comment by adamwathan** [comment]
Just tested and it is generated — are you just missing the `transform` class for it to take affect?

```
<div class="transform translate-x-[-9.5rem]"></div>
```

**Comment by pheuter** [comment]
Hm, weird, I have `transform-gpu` on it, will investigate further and see if there's something weird in my build process, thanks.

**Comment by pheuter** [comment]
Just some weirdness in my build process, sorry for bothering! @adamwathan 

p.s. tailwind-jit is absolutely wonderful ✨  thanks for all your work!

**Comment by adamwathan** [comment]
Cool no problem glad it is working! 🙌
