### ISSUE TITLE
Windows: ENOENT error — spaces in folder names

### ISSUE THREAD

**Issue by mrdarkside** [tailwindlabs/tailwindcss-jit#78]
Next.js project.

Webpack can't load css if path to the folder contains a space symbol.

It appears while using `"@tailwindcss/jit": {},` option and if I change space to underscore everything works fine.

Default `tailwindcss: {},` works in both cases.

Path that causes error:  `D:\p projects\clevr\styles\gobals.css`
Path tha works: `D:\p_projects\clevr\styles\gobals.css`

The error:

`error - ./styles/globals.css ((webpack)/css-loader/cjs.js??ref--5-oneOf-6-1!(webpack)/postcss-loader/cjs.js??ref--5-oneOf-6-2!./styles/globals.css)`
`Error: ENOENT: no such file or directory, stat '/p%20projects/clevr/tailwind.config.js'`

**Comment by laymonage** [comment]
See https://github.com/tailwindlabs/tailwindcss-jit/issues/22.
