### ISSUE TITLE
Extending animation to tailwind.config.js removes other all styles/classes

### ISSUE THREAD

**Issue by adalberth** [tailwindlabs/tailwindcss-jit#80]
When extending animations:

```
module.exports = {
    theme: {
        extend: {
            // ...
            animation: {
                'bounce-slow': 'bounce 3s ease-in-out infinite',
            },
        },
    },
}
```

It seems like it removes all other the styles.

Stack: Nuxt with nuxtjs/tailwindcss (with JIT turn on).
```
{
    "dependencies": {
        "core-js": "^3.8.3",
        "nuxt": "^2.14.12"
    },
    "devDependencies": {
        "@nuxtjs/tailwindcss": "^4.0.1",
        "postcss": "^8.2.8",
    }
}
```

**Comment by adalberth** [comment]
Since this is a new feature I dont really know if it's a nuxtjs/tailwindcss bug or a tailwindcss-jit bug – but I though that I should report it at the "source".

**Comment by silvenon** [comment]
I tried using your Tailwind configuration in an isolated test case and I was able to use Tailwind classes normally. 😄 If I misunderstood you, could you be more specific?

Generally when you're unsure which part of your stack is a problem, start with nothing and gradually add complexity until you figure out what exactly caused it, then report it here. 90% of the times I realize it was a "me" problem, so I'm glad I didn't ask the maintainers to take a look at a non-problem. 😃

**Comment by adamwathan** [comment]
Can't reproduce here:

<img width="936" alt="image" src="https://user-images.githubusercontent.com/4323180/111454067-9ed28c80-86ea-11eb-83e1-3f5388b9de98.png">

Going to close but if you can figure out a way to reproduce please open a new issue and include a link to a GitHub repo that reproduces the problem 👍🏻  There's a chance it's specific to the Nuxt module as well which unfortunately is out of our hands.

**Comment by adalberth** [comment]
After some testing around, I found that it happens on and off, not only with animations, therefor I think it's a nuxt/tailwindcss bug, so I'll report it there instead. Sorry for the inconvenience 🙈
