### ISSUE TITLE
Support for selectors in `important` option

### ISSUE THREAD

**Issue by frandiox** [tailwindlabs/tailwindcss-jit#85]
Hi! Thanks for all the updates.

It seems adding `important: '#app'` to the Tailwind config doesn't add any specificity to the classes. Same with `important: true`. I'm using `v0.1.1`.
It works as expected when switching back to `tailwindcss` in PostCSS file.

Thanks!

**Comment by thomaside** [comment]
It's documented under [Known Limitations](https://github.com/tailwindlabs/tailwindcss-jit#known-limitations) already.

**Comment by adamwathan** [comment]
Yep captured as a known limitation already but will keep this open to track it. We might not actually reimplement this one for the JIT — have some better ideas for solving the same problem but will have to see how they play out.

**Comment by adamwathan** [comment]
Available in latest release! 🥳
