### ISSUE TITLE
Vite import error

### ISSUE THREAD

**Issue by mammadataei** [tailwindlabs/tailwindcss-jit#86]
Hi, I have a project structured as a monorepo that uses `vite`, and all styles are in a separate package that I have imported as usual:

```css
@import '@org/package/path-to-file.css'
``` 

It used to work but when I change the `tailwindcss` to `@tailwindcss/jit` the import throws a can not find file error.

**Comment by deleonio** [comment]
I think that is a vite thing. You need to configure the vite config css like here: https://github.com/leanupjs/leanup/blob/549f5c0bbb988a1fed46b6a965e7ef70397701a0/packages/stack/vite/vite.config.js#L5

**Comment by silvenon** [comment]
@mammadataei can you share more info, or maybe a repo? I would like to take a look at it.

**Comment by mammadataei** [comment]
Thanks for your responses, The problem was because of whitespace in the package name.
