### ISSUE TITLE
Next.js: Infinite Fast Refresh loop Error

### ISSUE THREAD

**Issue by surjithctly** [tailwindlabs/tailwindcss-jit#87]
I installed tailwind-jit on a fresh create-next app. when I run `yarn dev` it goes in to an infinite loop of fast refresh. 

Here's a GIF to understand what I mean:

![eeeeee](https://user-images.githubusercontent.com/1884712/111427480-6794b900-86b3-11eb-8300-20c3112346b5.gif)
![eerrrreeee](https://user-images.githubusercontent.com/1884712/111427489-695e7c80-86b3-11eb-9ecd-d55904f275e3.gif)

Debug Info: 

- Fresh Create-Next-App
- Windows 10
- Node 14.16.0

Next.js does not provide much debug error here, so not sure what's the real cause. If you need any further debug info, let me know how I can grab those. 

Thanks a lot.

**Comment by bradlc** [comment]
Please could you provide a repository that reproduces the issue?

**Comment by surjithctly** [comment]
Hey @bradlc I tried to run it on a codesandbox and it worked fine there. 

So, it appears only in Windows 10 (Node 14.16.0)

The app is a fresh create-next-app with JIT installed. Nothing else.

**Comment by bradlc** [comment]
It works fine for me on Windows 10 and Node 14.16.0. Unfortunately it's not going to be possible to find the cause without a reproduction.

**Comment by marcfilleul** [comment]
Hi,
@surjithctly, I had a similar issue with eleventy and just solved it.

Following the documentation, I initially added the dist/public folder in my tailwind purge config (below is the documentation example):

```
purge: [
    './public/**/*.html',
    './src/**/*.{js,jsx,ts,tsx,vue}',
  ],
```

By simply removing the public folder form it, the infinite loop has stopped.

By the way, I wonder what is the purpose of adding the public folder here?

**Comment by surjithctly** [comment]
Wow.. @marcfilleul That was an easy fix. Thanks a million, dude. 

It did fix my issue. been scratching my head for the last two days, as it was working fine on a codesandbox.

**Comment by marcfilleul** [comment]
Happy to help, I was scratching my head too :)
