### ISSUE TITLE
IntelliSense: will be broken with jit?

### ISSUE THREAD

**Issue by klaasgeldof** [tailwindlabs/tailwindcss-jit#88]
First of all, great job on the jit compiler! It works like a charm 😀

As far as I understand how the Tailwind IntelliSense extension works, it looks at your config file and makes a list of all the classes that will be generated, and then groups them by variant to create some sort of lookup table in memory. As you're typing, it uses that lookup table to make suggestions. 

But with the jit compiler, how will that work? IntelliSense will be broken or at least will need to be rewritten in another way I guess?

**Comment by laymonage** [comment]
I'm guessing that the IntelliSense would be reworked to just assume all possible variants are enabled, and maybe provide some information about arbitrary values (`[some-value]`). Not sure if this will bloat the suggestions, though. It's also possible that the `variants` configuration (or a new configuration option) would be kept as a reference for IntelliSense (but not required for the classes to actually work).

**Comment by adamwathan** [comment]
It works pretty well already honestly — all it does is look at your config file and generate everything it needs behind the scenes. I'm using it with no issues in JIT projects for example. There are things we can add to it to make it even better (like autocompletion for stacked variants which isn't currently supported) but for the most part I think you'll find it's 99% there 👍🏻 

Going to close this, can track any IntelliSense improvements/issues over on that repo 👍🏻
